<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3.org/1999/xlink"
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="qualified">
  <!-- http://www.google.com/codesearch?hl=en&q=show:I92jahbSdAc:nlHf1ft_wFI:iiWWXEUEbBs&sa=N&ct=rd&cs_p=https://svn.sourceforge.net/svnroot/cogkit/trunk&cs_f=atct/service/xsd/activeTablesData/cmcs.xsd&start=1 -->
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="title" type="xs:string"/>
		<xs:attribute name="role" type="xs:string"/>
		<xs:attribute name="href" type="xs:string" />
		<xs:attribute name="show" type="xs:string"/>
		<xs:attribute name="actuate" type="xs:string"/>
		<xs:attribute name="label" type="xs:string"/>
		<xs:attribute name="from" type="xs:string"/>
		<xs:attribute name="to" type="xs:string"/>
	<xs:attributeGroup name="metadataLink">
	</xs:attributeGroup>
</xs:schema>
