<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.blogger.com/atom/ns#"
	xmlns:blogger="http://www.blogger.com/atom/ns#"
	xmlns:draft="http://purl.org/atom-blog/ns#"
	xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	jxb:version="1.0"
	elementFormDefault="unqualified">
	<xs:import namespace="http://purl.org/atom-blog/ns#" schemaLocation="bloggerDraft.xsd"/>
	<xs:element name="bloggerExtension">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="blogger:convertLineBreaks" />
				<xs:element ref="draft:draft" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:annotation>
		<xs:documentation>
			Blogger Atom extension http://code.blogger.com/archives/atom-docs.html#extensions
		</xs:documentation>
	</xs:annotation>
 	<xs:element name="convertLineBreaks" type="xs:boolean" />
</xs:schema>
