<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	targetNamespace="http://purl.org/rss/1.0/modules/syndication/"
	elementFormDefault="qualified">

	<xs:annotation>
		<xs:documentation>
			RDF Syndication module
		</xs:documentation>
	</xs:annotation>
<!--
Description

Provides syndication hints to aggregators and others picking up this RDF Site Summary (RSS) feed regarding how often it is updated. 
For example, if you updated your file twice an hour, updatePeriod would be "hourly" and updateFrequency would be "2". 
The syndication module borrows from Ian Davis's Open Content Syndication (OCS) directory format. 
It supercedes the RSS 0.91 skipDay and skipHour elements.

updatePeriod
Describes the period over which the channel format is updated. Acceptable values are: hourly, daily, weekly, monthly, yearly. 
If omitted, daily is assumed.

updateFrequency
Used to describe the frequency of updates in relation to the update period. A positive integer indicates how many times in 
that period the channel is updated. For example, an updatePeriod of daily, and an updateFrequency of 2 indicates the channel 
format is updated twice daily. If omitted a value of 1 is assumed.

updateBase
Defines a base date to be used in concert with updatePeriod and updateFrequency to calculate the publishing schedule. 
The date format takes the form: yyyy-mm-ddThh:mm 
 
 -->
 	<xs:element name="updatePeriod" type="sy:UpdatePeriodEnum">
		<xs:annotation>
			<xs:documentation>Describes the period over which the channel format is updated. Acceptable values are: hourly, daily, weekly, monthly, yearly. 
			If omitted, daily is assumed.</xs:documentation>
		</xs:annotation>
		
 	</xs:element>
 	
 	<xs:simpleType name="UpdatePeriodEnum">
			<xs:restriction base="xs:string">
				<xs:enumeration value="hourly" />
				<xs:enumeration value="daily" />
				<xs:enumeration value="weekly" />
				<xs:enumeration value="monthly" />
				<xs:enumeration value="yearly" />
			</xs:restriction>
	</xs:simpleType>

	<xs:element name="updateFrequency" type="xs:positiveInteger" >
		<xs:annotation>
			<xs:documentation>Used to describe the frequency of updates in relation to the update period. 
			A positive integer indicates how many times in that period the channel is updated. For example, 
			an updatePeriod of daily, and an updateFrequency of 2 indicates the channel format is updated twice daily. 
			If omitted a value of 1 is assumed.
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="updateBase" type="xs:string" >
		<xs:annotation>
			<xs:documentation>Defines a base date to be used in concert with updatePeriod and 
			updateFrequency to calculate the publishing schedule. 
			The date format takes the form: yyyy-mm-ddThh:mm</xs:documentation>
		</xs:annotation>	
	</xs:element>	

</xs:schema>
